language: python
python:
  - "3.5"
  - "3.6"

notifications:
  email: false

install:
  - pip install -e .[testing]
  - pip install
  - pip install coveralls

script: nosetests --with-coverage --cover-package=wcxf

after_success: coveralls
