language: python
python:
  - "3.5"
  - "3.6"

notifications:
  email: false

install:
  - pip install -e .[testing]
  - pip install coveralls

script:
  - echo 'import coverage; coverage.process_startup()' > sitecustomize.py
  - COVERAGE_PROCESS_START=.coveragerc nosetests --with-coverage --cover-package=wcxf

after_success: coveralls
